<?php

  # Google Maps API Quick Ref: <http://code.google.com/intl/en-US/apis/maps/documentation/reference.html>

  # access counter
    include('simple-counter.php');
    $hits        = counted();
    $created     = "21/04/2009 Ter 16:59:43";
    $counted     = "23/04/2009 Qui 08:22:05";

    include('lib.php');

    $data        = include('data.php');
    $months      = $data['months'];
    $definitions = $data['definitions'];
    $ephemeris   = $data['ephemeris'];

  # $day         = 22;
  # $month       = 4;
  # $year        = 2009;

    $title       = "Cálculo de Eventos Astronômicos";

    $now_ts      = time();

    $def_day     = date('j', $now_ts);
    $def_month   = date('n', $now_ts);
    $def_year    = date('Y', $now_ts);

    $day         = str_pad( isset($_POST['day'  ]) && ! isset($_POST['today']) ? $_POST['day'  ] : $def_day   ,2,0,STR_PAD_LEFT);
    $month       = str_pad( isset($_POST['month']) && ! isset($_POST['today']) ? $_POST['month'] : $def_month ,2,0,STR_PAD_LEFT);
    $year        =          isset($_POST['year' ]) && ! isset($_POST['today']) ? $_POST['year' ] : $def_year;

    $lastday     = date('t', mktime(0, 0, 0, $month, 1, $year));

    foreach(array_keys($months) as $m)
    {
      $selected    = $m==$month ? " selected" : "";
      $month_list .= "<option value=\"$m\"$selected>{$months[$m]}</option>\n";
    }

    for($d=1; $d<=$lastday; $d++)
    {
      $selected  = $d==$day || $d==$lastday && $day>=$lastday ? " selected" : "";
      if ($day>$lastday) $day = $lastday;
      $padded_d  = str_pad($d,2,0,STR_PAD_LEFT);
      $day_list .= "<option value=\"$d\"$selected>$padded_d</option>\n";
    }

  # CEAT
    $def_addr    = "Rua Alberto Torres, 297, Lajeado, RS, Brasil";
    $def_lat     = -29.4635114818812;	# 29° 27' 48" (0.64133477232") S
    $def_long    = -51.9643307290972;	# 51° 57' 51" (0.59062474992") W
  # $def_lat     = -(29 + 27/60 + 48/60/60);
  # $def_long    = -(51 + 57/60 + 51/60/60);
    $def_zenith  = "";

    $lat         = isset($_POST['lat'   ]) ? $_POST['lat'   ] : $def_lat;
    $long        = isset($_POST['long'  ]) ? $_POST['long'  ] : $def_long;
    $zenith      = isset($_POST['zenith']) ? $_POST['zenith'] : $def_zenith;

    $zoom        = 17;               # 0..19
    $ctrl_size   = "large";
#   $ctrl_size   = "small";

  # $maptype     = "normal";         # mapa de ruas comum (default)
    $maptype     = "satellite";      # imagens de satélite
  # $maptype     = "hybrid";         # camada transparente das principais ruas nas imagens de satélite
  # $maptype     = "physical";       # mapas com características físicas como terreno e vegetação. Este tipo de mapa não é exibido dentro dos controles de tipo de mapa por padrão
  # $maptype     = "moon_elevation"; # mapa plano sombreado na superfície da Lua, com altitudes diferenciadas por cores. Este tipo de mapa não é exibido dentro dos controles de tipo de mapa por padrão
  # $maptype     = "moon_visible";   # fotografias tiradas da órbita da Lua. Este tipo de mapa não é exibido dentro dos controles de tipo de mapa por padrão
  # $maptype     = "mars_elevation"; # mapa em relevo sombreado na superfície de Marte, com altitudes diferenciadas por cores. Este tipo de mapa não é exibido dentro dos controles de tipo de mapa por padrão
  # $maptype     = "mars_visible";   # fotografias tiradas da órbita de Marte. Este tipo de mapa não é exibido dentro dos controles de tipo de mapa por padrão
  # $maptype     = "mars_infrared";  # mapa infravermelho sombreado na superfície de Marte, no qual as áreas quentes aparecem brilhantes e as áreas frias aparecem escuras
  # $maptype     = "sky_visible";    # mosaico do céu, abrangendo toda a esfera celeste

    $zeniths     = array( 'p' => $zenith, 'o' => 90+50/60, 'c' => 96, 'n' => 102, 'a' => 108, );
    $rise        = array( 'r' => true, 's' => false, );

    $prec        = 0;

    $gmapi_key   = "ABQIAAAA-BORWsCJ20Pw-hql1POcbRQvDi3NjDgQt-Dt7uX1yK-KFt-x-hRRcuHWEV1uN6eOj6XaCF5cSe2HhQ"; # www.ceat.net
    $width       = 500;
    $height      = 500;

    $ctrl_size   = ucfirst($ctrl_size);
    $maptype     = 'G_'.strtoupper($maptype).'_MAP';

#   $help        = "../image/help.png";
    $help        = "../image/bluetooth.png";

    foreach (array_keys($zeniths) as $z)
    {
      foreach (array_keys($rise) as $r) $t[$z][$r] = suntime($day, $month, $year, $lat, $long, $zeniths[$z], $rise[$r], $prec);
      $l[$z][0] = $t[$z]['s'][0] - $t[$z]['r'][0];
      $dh = $l[$z][0];
      $ih = sprintf('%02d',intval($dh));
      $dm = ($dh-$ih)*60;
      $im = sprintf('%02d',intval($dm));
      $ds = ($dm-$im)*60;
      $is = sprintf('%02d',intval($ds));
      if ($prec!=0) $dd = ltrim(number_format($ds-$is,$prec),0);
      $l[$z][1] = "$ih:$im:$is$dd";
    }


    foreach (array_keys($definitions) as $key)
    {
      $url = $definitions[$key][1]=='wp' ? "pt.wikipedia.org/wiki/".$definitions[$key][0] : $definitions[$key][1];
      $def_divs .= "<div id=\"$key\" class=\"popup tooltip\" onmouseover=\"ppopen('$key',0,event)\" onmouseout=\"ppclose('$key',false)\"><a href=\"http://$url\" target=\"_blank\" class=\"definicao\">{$definitions[$key][0]}</a>{$definitions[$key][2]}</div>\n";
    }


    print "
<html>

<head>

  <title>[Audax do Vale] $title</title>

  <script src=\"http://maps.google.com/maps?file=api&v=2&key=$gmapi_key\" type=\"text/javascript\"></script>

  <script type=\"text/javascript\">

    function load()
    {

      if (GBrowserIsCompatible())
      {

        var map = new GMap2(document.getElementById(\"map\"));
        map.addControl(new G{$ctrl_size}MapControl());
        map.addControl(new GMapTypeControl());
//      var center = new GLatLng($lat, $long);
        var center = new GLatLng(document.getElementById('input_lat').value, document.getElementById('input_long').value);
        map.setCenter(center, $zoom);
        map.setMapType($maptype);
        geocoder = new GClientGeocoder();
        var marker = new GMarker(center, {draggable: true});
        map.addOverlay(marker);
        document.getElementById(\"lat\").innerHTML = center.lat().toFixed(5);
        document.getElementById(\"lng\").innerHTML = center.lng().toFixed(5);

        GEvent.addListener(marker, \"dragend\", function()
        {
          var point = marker.getPoint();
          map.panTo(point);
          document.getElementById(\"lat\").innerHTML = point.lat().toFixed(5);
          document.getElementById(\"lng\").innerHTML = point.lng().toFixed(5);

        } );


        GEvent.addListener(map, \"moveend\", function()
        {
          map.clearOverlays();
          var center = map.getCenter();
          var marker = new GMarker(center, {draggable: true});
          map.addOverlay(marker);
          document.getElementById(\"lat\").innerHTML = center.lat().toFixed(5);
          document.getElementById(\"lng\").innerHTML = center.lng().toFixed(5);
          GEvent.addListener(marker, \"dragend\", function()
          {
            var point = marker.getPoint();
            map.panTo(point);
            document.getElementById(\"lat\").innerHTML = point.lat().toFixed(5);
            document.getElementById(\"lng\").innerHTML = point.lng().toFixed(5);
          } );
        } );

      }

    }

    function showAddress(address)
    {
      var map = new GMap2(document.getElementById(\"map\"));
      map.addControl(new G{$ctrl_size}MapControl());
      map.addControl(new GMapTypeControl());
      if (geocoder)
      {
        geocoder.getLatLng(address, function(point)
        {
          if (!point)
          {
            alert(address + \" not found\");
          }
          else
          {
            document.getElementById(\"lat\").innerHTML = point.lat().toFixed(5);
            document.getElementById(\"lng\").innerHTML = point.lng().toFixed(5);
            map.clearOverlays()
            map.setCenter(point, $zoom);
            map.setMapType($maptype);
            var marker = new GMarker(point, {draggable: true});
            map.addOverlay(marker);
            GEvent.addListener(marker, \"dragend\", function()
            {
              var pt = marker.getPoint();
              map.panTo(pt);
              document.getElementById(\"lat\").innerHTML = pt.lat().toFixed(5);
              document.getElementById(\"lng\").innerHTML = pt.lng().toFixed(5);
            } );
            GEvent.addListener(map, \"moveend\", function()
            {
              map.clearOverlays();
              var center = map.getCenter();
              var marker = new GMarker(center, {draggable: true});
              map.addOverlay(marker);
              document.getElementById(\"lat\").innerHTML = center.lat().toFixed(5);
              document.getElementById(\"lng\").innerHTML = center.lng().toFixed(5);
              GEvent.addListener(marker, \"dragend\", function()
              {
                var pt = marker.getPoint();
                map.panTo(pt);
                document.getElementById(\"lat\").innerHTML = pt.lat().toFixed(5);
                document.getElementById(\"lng\").innerHTML = pt.lng().toFixed(5);
              } );
            } );
          }
        } );
      }
    }

    function ppopen(id,tout,evt)
    {
      var offsetX = 0;
      var offsetY = 15;

      var offsetX = -10;
      var offsetY = -10;

      var x, y;

      if (document.all)
      { // IE
        x  = document.documentElement && document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft;
        y  = document.documentElement && document.documentElement.scrollTop  ? document.documentElement.scrollTop  : document.body.scrollTop;
        x += window.event.clientX;
        y += window.event.clientY;
      }
      else
      { // browsers bem feitos
        x = evt.pageX;
        y = evt.pageY;
      }
      document.getElementById(id).style.left = (x + offsetX) + \"px\";
      document.getElementById(id).style.top  = (y + offsetY) + \"px\";

      document.getElementById(id).style.display = 'block';
      if (tout>0)
      {
        sto = setTimeout(\"ppclose('\"+id+\"',false)\", 1000*tout);
      }
      else
      {
        document.getElementById('address').value = document.getElementById('input_lat').value+', '+document.getElementById('input_long').value;
        document.getElementById('find').click();
        document.getElementById('address').value = '';
      }
    }

    function ppclose(id,tranfer)
    {
      if (tranfer)
      {
        document.getElementById('input_lat').value  = document.getElementById('lat').innerHTML;
        document.getElementById('input_long').value = document.getElementById('lng').innerHTML;
      }
      document.getElementById(id).style.display = 'none';
      clearTimeout(sto);
    }

    function processKey(e,submit)
    {
      if (e         == null) e = window.event;
      if (e.keyCode ==   13) submit.click();
    }

  </script>

  <style type=\"text/css\">

    .popup
    {
      position: absolute;
      padding: 10px;
      border: 1px solid #ffa200;
      background: #fffbcf;
      display: none;
      z-index: 99;
    }

    .tooltip
    {
      padding: 0 3px;
      background: #dfebff;
      border-color: #0057bf;
    }

    .definicao
    {
      text-decoration: none;
      display: block;
      font-weight: bold;
      border-bottom: 1px dotted #0057bf;
    }

    h2
    {
      margin: 0 0 5px 0;
      text-align: center;
    }

    .rline>td
    {
      background: #dfdfdf;
      padding: 5px;
    }

    td, th
    {
      vertical-align: top;
      padding: 0 5px;
    }

    img
    {
      cursor: pointer;
    }

    form
    {
      margin: 0;
    }

  </style>

</head>

<body onload=\"load()\" onunload=\"GUnload()\">

<h1>$title</h1>

<div id=\"getcoord\" class=\"popup\">
  <form name=\"find_form\" method=\"post\" onmouseover=\"document.onkeypress=processKey(document.find_form.find)\" onsubmit=\"showAddress(this.address.value); return false\">
    <input type=\"text\" size=\"54\" name=\"address\" id=\"address\" value=\"\" onmouseover=\"ppopen('usage',5,event)\" onmouseout=\"ppclose('usage',false)\" />
    <input type=\"submit\" id=\"find\" value=\"Localizar\" />
    <input type=\"button\" onclick=\"ppclose('getcoord',true)\" value=\"Fechar\" />
  </form>
  <table>
  <tr>
    <td><b>Latitude</b></td>  <td id=\"lat\"></td>
    <td width=20></td>
    <td><b>Longitude</b></td> <td id=\"lng\"></td>
  </tr>
  </table>
  <div align=\"center\" id=\"map\" style=\"width:{$width}px; height:{$height}px\"><br/></div>
</div>

<div id=\"usage\" class=\"popup tooltip\">
  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">
  <tr> <td rowspan=\"2\" valign=\"top\" style=\"padding-right:10px\"><b>Ex:</b></td> <td style=\"padding-right:10px; text-align:right;\"><i>(endereço)</i></td>  <td>$def_addr</td>       </tr>
  <tr>                                                                               <td style=\"padding-right:10px; text-align:right;\"><i>(lat, long)</i></td> <td>$def_lat, $def_long</td> </tr>
  </table>
</div>


<form name=\"input_form\" method=\"post\" onmouseover=\"document.onkeypress=processKey(document.input_form.exec)\">
  <table border=\"0\" cellpadding=\"0\" cellspacing=\"3\">
  <tr>
    <td>Data</td>
    <td colspan=\"2\">
      <input type=\"text\" name=\"year\" value=\"$year\" size=\"4\" maxlength=\"4\" tabindex=\"1\">
      <select name=\"month\" onchange=\"submit()\" tabindex=\"2\">\n$month_list</select>
      <select name=\"day\" tabindex=\"3\">\n$day_list</select>
      <input type=\"submit\" name=\"today\" value=\"Hoje\" tabindex=\"8\">
    </td>
  </tr>
  <tr> <td>Latitude<img src=\"$help\" onclick=\"ppopen('latitude',0,event)\" /></td>    <td><input type=\"text\" name=\"lat\"    value=\"$lat\"    tabindex=\"4\" id=\"input_lat\"  /></td> <td style=\"padding:0\" rowspan=\"2\"><img src=\"../image/earth_api.gif\" onclick=\"ppopen('getcoord',0,event)\" alt=\"[Earth API]\"\" /></td></tr>
  <tr> <td>Longitude<img src=\"$help\" onclick=\"ppopen('longitude',0,event)\" /></td>  <td><input type=\"text\" name=\"long\"   value=\"$long\"   tabindex=\"5\" id=\"input_long\" /></td> </tr>
  <tr> <td>Dist. Zenital<img src=\"$help\" onclick=\"ppopen('zenite',0,event)\" /></td> <td><input type=\"text\" name=\"zenith\" value=\"$zenith\" tabindex=\"6\" /></td>                   <td style=\"padding:0\">(opcional)</td> </tr>
  <tr> <td align=\"center\" colspan=\"3\"><input type=\"submit\" name=\"exec\" value=\"Calcular\"  tabindex=\"7\"></td> </tr>
  </table>
</form>

<table border=\"0\" cellpadding=\"10\" cellspacing=\"10\" id=\"results\">
<tr class=\"rline\"> <td colspan=\"2\"><h2>Localização Espaço-Temporal</h2></td>
<tr>
  <td colspan=\"2\">

    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">
    <tr> <th align=\"left\">Latitude</th>      <td>$lat</td>              </tr>
    <tr> <th align=\"left\">Longitude</th>     <td>$long</td>             </tr>
    <tr> <th align=\"left\">Dist. Zenital</th> <td>$zenith</td>           </tr>
    <tr> <th align=\"left\">Data</th>          <td>$day/$month/$year</td> </tr>
    </table>

  </td>
</tr>
<tr class=\"rline\"> <td colspan=\"2\"><h2>Efemérides<img src=\"$help\" onclick=\"ppopen('efemerides',0,event)\" /> Solares</h2></td>
</tr>
<tr>
  <td align=\"right\">

    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\">
    <tr> <th>Crepúsculo<img src=\"$help\" onclick=\"ppopen('crepusculo',0,event)\" /></th>                  <th colspan=\"2\">Dist. Zenital</th> <th>Nascimento</th>                         <th>Ocaso<img src=\"$help\" onclick=\"ppopen('ocaso',0,event)\" /></th> <th>Duração</th>                       </tr>
    ".($zenith==""?"":"<tr> <td></td>                                                                       <td>{$zenith}°</td> <td></td>        <td align=\"center\">{$t['p']['r'][1]}</td> <td align=\"center\">{$t['p']['s'][1]}</td>                                              <td>{$l['p'][1]}</td> </tr>")."
    <tr> <td align=\"left\">Oficial<img src=\"$help\" onclick=\"ppopen('oficial',0,event)\" /></td>         <td>90° 50'</td>    <td>0.83°</td>   <td align=\"center\">{$t['o']['r'][1]}</td> <td align=\"center\">{$t['o']['s'][1]}</td>                                              <td>{$l['o'][1]}</td> </tr>
    <tr> <td align=\"left\">Civil<img src=\"$help\" onclick=\"ppopen('civil',0,event)\" /></td>             <td>96°</td>        <td>6°</td>      <td align=\"center\">{$t['c']['r'][1]}</td> <td align=\"center\">{$t['c']['s'][1]}</td>                                              <td>{$l['c'][1]}</td> </tr>
    <tr> <td align=\"left\">Náutico<img src=\"$help\" onclick=\"ppopen('nautico',0,event)\" /></td>         <td>102°</td>       <td>12°</td>     <td align=\"center\">{$t['n']['r'][1]}</td> <td align=\"center\">{$t['n']['s'][1]}</td>                                              <td>{$l['n'][1]}</td> </tr>
    <tr> <td align=\"left\">Astronômico<img src=\"$help\" onclick=\"ppopen('astronomico',0,event)\" /></td> <td>108°</td>       <td>18°</td>     <td align=\"center\">{$t['a']['r'][1]}</td> <td align=\"center\">{$t['a']['s'][1]}</td>                                              <td>{$l['a'][1]}</td> </tr>
    </table>

  </td>
  <td>

    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\">
    <tr> <th align=\"left\">Ano</th>                                                                               <td colspan=2>$year</td>                       </tr>
    <tr> <th align=\"left\">Periélio<img src=\"$help\"  onclick=\"ppopen('perielio',0,event)\" /></th>             <td>01</td> <td>{$ephemeris[$year]['pe']}</td> </tr>
    <tr> <th align=\"left\">Equinócio<img src=\"$help\" onclick=\"ppopen('equinocio',0,event)\" /> de Outono</th>  <td>03</td> <td>{$ephemeris[$year]['e1']}</td> </tr>
    <tr> <th align=\"left\">Solstício<img src=\"$help\" onclick=\"ppopen('solsticio',0,event)\" /> de Inverno</th> <td>06</td> <td>{$ephemeris[$year]['s1']}</td> </tr>
    <tr> <th align=\"left\">Afélio<img src=\"$help\"    onclick=\"ppopen('afelio',0,event)\" /></th>               <td>07</td> <td>{$ephemeris[$year]['ae']}</td> </tr>
    <tr> <th align=\"left\">Equinócio de Primavera</th>                                                            <td>09</td> <td>{$ephemeris[$year]['e2']}</td> </tr>
    <tr> <th align=\"left\">Solstício de Verão</th>                                                                <td>12</td> <td>{$ephemeris[$year]['s2']}</td> </tr>
    </table>

  </td>
</tr>
<tr class=\"rline\"> <td colspan=\"2\"><h2>Efemérides Lunares</h2></td>
<tr>
  <td align=\"right\">

    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\">
    <tr> <th align=\"left\">Nascimento</th>     <td></td> </tr>
    <tr> <th align=\"left\">Meio-Dia Lunar</th> <td></td> </tr>
    <tr> <th align=\"left\">Ocaso</th>          <td></td> </tr>
    <tr> <th align=\"left\">Duração</th>        <td></td> </tr>
    <tr> <th align=\"left\">Aparência</th>      <td></td> </tr>
    </table>

  </td>
  <td>

    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\">
    <tr> <th align=\"left\">Mês</th>        <td colspan=2>$month</td> </tr>
    <tr> <th align=\"left\">Nova</th>       <td></td> <td></td>       </tr>
    <tr> <th align=\"left\">Crescente</th>  <td></td> <td></td>       </tr>
    <tr> <th align=\"left\">Cheia</th>      <td></td> <td></td>       </tr>
    <tr> <th align=\"left\">Minguante</th>  <td></td> <td></td>       </tr>
    <tr> <th align=\"left\">Perigeu<img src=\"$help\" onclick=\"ppopen('perigeu',0,event)\" /></th>    <td></td> <td></td>       </tr>
    <tr> <th align=\"left\">Apogeu<img src=\"$help\" onclick=\"ppopen('apogeu',0,event)\" /></th>     <td></td> <td></td>       </tr>
    </table>

  </td>
</tr>
</table>

<img src=\"$help\" onclick=\"ppopen('bluetooth',0,event)\" />, porque <a href=\"http://www.youtube.com/watch?v=61a0qHFcQE4\" target=\"_blank\">tudo fica melhor com Bluetooth</a>...

$def_divs

</body>

</html>
";



?>
